version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: studio-mongodb
    restart: unless-stopped
    environment:
      # Use environment variables for MongoDB credentials
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-studio-gallery}
    ports:
      - "0:27017"  # Auto-assign any available port
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - studio-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studio-app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      # Authentication - NEVER hardcode these values
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      
      # AI Configuration
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      
      # Database Configuration - Dynamic based on container networking
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME:-studio-gallery}?authSource=admin
      
      # Application Configuration
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      APP_NAME: ${APP_NAME:-AI Gallery Studio}
      APP_URL: ${APP_URL}
      
      # Production settings
      NODE_ENV: production
      PORT: 3000
    ports:
      - "${APP_PORT:-9002}:3000"  # Try configured port, fallback to 9002
    networks:
      - studio-network
    volumes:
      # Only mount volumes for uploads if needed, never mount source code in production
      - app_uploads:/app/public/uploads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  studio-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  app_uploads:
    driver: local
